# Generated by Django 5.2.7 on 2025-10-28 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_carrito_detallecarrito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='detallecarrito',
            options={'ordering': ['-id'], 'verbose_name': 'Detalle de Carrito', 'verbose_name_plural': 'Detalles de Carrito'},
        ),
        migrations.AlterUniqueTogether(
            name='detallecarrito',
            unique_together={('carrito', 'producto')},
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del producto al momento de agregarlo al carrito', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='precio',
        ),
    ]
