# Generated by Django 5.2 on 2025-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_carrito_options_alter_detallecarrito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='notificado_stock_bajo',
            field=models.BooleanField(default=False),
        ),
    ]
