# Generated by Django 5.2 on 2025-11-13 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTATICO', 'Estático'), ('PERSONALIZADO', 'Personalizado'), ('NATURAL', 'Lenguaje Natural')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('consulta_original', models.TextField(help_text='Configuración JSON o texto de consulta')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('tiempo_generacion', models.FloatField(default=0.0, help_text='Tiempo en segundos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
