# Generated by Django 5.2 on 2025-11-18 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_alter_cliente_usuario_alter_empleado_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token FCM del dispositivo', max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', help_text='Plataforma del dispositivo', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el token está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del token')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del token')),
                ('user', models.ForeignKey(help_text='Usuario propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de dispositivo',
                'verbose_name_plural': 'Tokens de dispositivos',
                'db_table': 'device_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'), models.Index(fields=['token'], name='device_toke_token_e218ea_idx')],
            },
        ),
    ]
