"""
Django settings for backend_exa2 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import dj_database_url
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-key-never-use-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Configuración de ALLOWED_HOSTS para Railway
RAILWAY_PUBLIC_DOMAIN = config('RAILWAY_PUBLIC_DOMAIN', default='')
RAILWAY_STATIC_URL = config('RAILWAY_STATIC_URL', default='')

# Indicar a Django que está detrás de un proxy que termina TLS (Railway)
# Esto es clave para que las cookies "secure" funcionen correctamente
# y no se produzca el bucle de login en /admin.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "backend-smart-production-c094.up.railway.app", "192.168.0.11"]

if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

if RAILWAY_STATIC_URL:
    domain = RAILWAY_STATIC_URL.replace('https://', '').replace('http://', '')
    ALLOWED_HOSTS.append(domain)

# Para desarrollo local con tu IP
if DEBUG:
    ALLOWED_HOSTS.append("192.168.0.11")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'perfiles',
    'inventario',
    'transacciones',
    'analitica',
     # Paquetes externos
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    
        # Paquetes para autenticación
        'rest_framework_simplejwt',
        'corsheaders',
]

# Configuración de autenticación JWT para DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT: Duración de sesión (tokens)
# Acceso: 1 hora | Refresh: 7 días (con rotación y blacklist)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_exa2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_exa2.wsgi.application'


# Database
# Usar DATABASE_URL si está disponible (Railway), sino usar SQLite para desarrollo
DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/La_Paz'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (archivos subidos por usuarios y reportes generados)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de almacenamiento
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS: permitir peticiones desde tu frontend local (ej: React en puerto 5173 o 3000)
CORS_ALLOWED_ORIGINS = [
    "https://frontend-smart-production-1256.up.railway.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://192.168.100.6",
]

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Agregar dominio de Railway si existe
if RAILWAY_PUBLIC_DOMAIN:
    CORS_ALLOWED_ORIGINS.extend([
        f"https://{RAILWAY_PUBLIC_DOMAIN}",
        f"http://{RAILWAY_PUBLIC_DOMAIN}",
    ])

# Agregar dominio de Railway a CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "https://frontend-smart-production-1256.up.railway.app",
    "https://backend-smart-production-c094.up.railway.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://192.168.100.6",
]

# Agregar dominio de Railway a CSRF trusted origins
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.extend([
        f"https://{RAILWAY_PUBLIC_DOMAIN}",
        f"http://{RAILWAY_PUBLIC_DOMAIN}",
    ])

# Para desarrollo con apps móviles, permitir todos los orígenes
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True



# ImgBB API Configuration
# Obtén tu API Key en: https://api.imgbb.com/
API_KEY_IMGBB = config('API_KEY_IMGBB', default='')

# Stripe API Configuration
# Configuración para pagos con Stripe
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Firebase Cloud Messaging Configuration
# Configuración para notificaciones push
FIREBASE_PROJECT_ID = config('FIREBASE_PROJECT_ID', default='smartsales360')

# Cargar credenciales desde archivo JSON
FIREBASE_SERVICE_ACCOUNT_FILE = BASE_DIR / 'smartsales360-fd434-firebase-adminsdk-fbsvc-a1b619cdf2.json'
if FIREBASE_SERVICE_ACCOUNT_FILE.exists():
    import json
    with open(FIREBASE_SERVICE_ACCOUNT_FILE, 'r') as f:
        FIREBASE_SERVICE_ACCOUNT_JSON = json.dumps(json.load(f))
else:
    FIREBASE_SERVICE_ACCOUNT_JSON = config('FIREBASE_SERVICE_ACCOUNT_JSON', default='')

