# Generated by Django 5.2.7 on 2025-11-10 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_carrito_options_alter_detallecarrito_options_and_more'),
        ('perfiles', '0002_alter_cliente_usuario_alter_empleado_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_comprobante', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_venta', to='perfiles.cliente')),
            ],
            options={
                'verbose_name': 'Nota de Venta',
                'verbose_name_plural': 'Notas de Venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('nota_venta', models.OneToOneField(help_text='Nota de venta asociada al pago', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pago', serialize=False, to='transacciones.notadeventa')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha del pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=10)),
                ('moneda', models.CharField(default='USD', help_text='Moneda del pago (USD, BOB, etc.)', max_length=10)),
                ('total_stripe', models.CharField(help_text='ID de pago en Stripe (payment_intent_id)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaDeVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_venta', to='inventario.producto')),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='transacciones.notadeventa')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Venta',
                'verbose_name_plural': 'Detalles de Nota de Venta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ListadoHistoricoVentas',
            fields=[
                ('nota_venta', models.OneToOneField(help_text='Nota de venta asociada a esta venta', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='historial_venta', serialize=False, to='transacciones.notadeventa')),
                ('cliente_nombre', models.CharField(help_text='Nombre completo del cliente', max_length=200)),
                ('cliente_ci', models.CharField(help_text='CI del cliente', max_length=20)),
                ('cliente_email', models.EmailField(blank=True, help_text='Email del cliente', max_length=254, null=True)),
                ('numero_venta', models.CharField(help_text='Número de comprobante de la venta', max_length=50, unique=True)),
                ('fecha_venta', models.DateTimeField(help_text='Fecha y hora de la venta')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal de la venta', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la venta', max_digits=10)),
                ('metodo_pago', models.CharField(default='Stripe', help_text='Método de pago utilizado', max_length=50)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('anulado', 'Anulado')], default='pendiente', help_text='Estado del pago', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, help_text='Fecha en que se completó el pago', null=True)),
                ('referencia_pago', models.CharField(blank=True, help_text='ID de referencia del pago (Stripe payment_intent_id)', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas u observaciones de la venta', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el histórico')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name': 'Historial de Venta',
                'verbose_name_plural': 'Listado Histórico de Ventas',
                'ordering': ['-fecha_venta'],
                'indexes': [models.Index(fields=['-fecha_venta'], name='transaccion_fecha_v_697ca6_idx'), models.Index(fields=['estado_pago'], name='transaccion_estado__cf4686_idx'), models.Index(fields=['cliente_ci'], name='transaccion_cliente_57a478_idx'), models.Index(fields=['numero_venta'], name='transaccion_numero__0d3c61_idx')],
            },
        ),
    ]
