# Generated by Django 5.2 on 2025-11-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadohistoricoventas',
            name='cliente_ci',
            field=models.CharField(blank=True, help_text='CI del cliente', max_length=20, null=True),
        ),
    ]
